name: refilc_kreta_api
publish_to: "none"

environment:
  sdk: ">=3.3.2 <=3.6.0"

dependencies:
  flutter:
    sdk: flutter
  refilc:
    path: ../refilc/
  http: ^1.1.2
  provider: ^6.1.1
  file_picker: ^8.0.5
  intl: ^0.19.0
  i18n_extension: ^12.0.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^4.0.0
