name: refilc_kreta_api
publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  refilc:
    path: ../refilc/
  http: ^1.3.0
  provider: ^6.1.2
  file_picker: ^8.3.7
  intl: ^0.19.0
  i18n_extension: ^12.0.1
  uuid: ^4.5.1

dependency_overrides:
  webview_flutter_wkwebview: 3.17.0

dev_dependencies:
  flutter_lints: ^5.0.0
