name: refilc_plus
publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # reFilc Main
  refilc:
    path: ../refilc/
  # e-KRETA API (kreten) client
  refilc_kreta_api:
    path: ../refilc_kreta_api/
  # reFilc Mobile UI
  refilc_mobile_ui:
    path: "../refilc_mobile_ui/"

  provider: ^6.1.1
  flutter_feather_icons: ^2.0.0+1
  uni_links: ^0.5.1
  url_launcher: ^6.2.5
  dropdown_button2: ^2.3.9
  home_widget: ^0.7.0+1
  image_picker: ^1.0.7
  image_crop: ^0.4.1
  animations: ^2.0.11
  flutter_svg: ^2.0.10+1
  flutter_dynamic_icon: ^2.1.0
  # android_dynamic_icon: ^2.0.0
  i18n_extension: ^12.0.1
  http: ^1.2.0
  fl_chart: ^0.68.0
  flutter_dynamic_icon_plus: ^1.1.2
  share_plus: ^10.0.3
  path_provider: ^2.1.3
  file_picker: ^8.0.5

dependency_overrides:
  webview_flutter_wkwebview: 3.17.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
