name: refilc_desktop_ui
publish_to: "none"

environment:
  sdk: ">=3.3.2 <=3.4.3"

dependencies:
  flutter:
    sdk: flutter

  # reFilc Main
  refilc:
    path: ../refilc/
  # e-KRETA API (kreten) client
  refilc_kreta_api:
    path: ../refilc_kreta_api/
  # reFilc Plus
  refilc_plus:
    path: ../refilc_plus/
  # reFilc Mobile
  refilc_mobile_ui:
    path: ../refilc_mobile_ui/

  cupertino_icons: ^1.0.2
  flutter_feather_icons: ^2.0.0+1
  provider: ^6.1.1
  url_launcher: ^6.2.5
  flutter_linkify: ^6.0.0
  flutter_markdown: ^0.6.20+1
  animations: ^2.0.11
  confetti: ^0.7.0
  auto_size_text: ^3.0.0
  flutter_acrylic: ^1.1.3
  elegant_notification: ^1.13.0
  flutter_staggered_grid_view: ^0.7.0
  i18n_extension: ^12.0.1
  flutter_expandable_fab: ^2.0.0
  collection: ^1.18.0
  animated_list_plus: ^0.5.2
  intl: ^0.19.0
  flutter_custom_tabs: ^2.0.0+1

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
