name: refilc_mobile_ui
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # reFilc Main
  refilc:
    path: ../refilc/
  # e-KRETA API (kreten) client
  refilc_kreta_api:
    path: ../refilc_kreta_api/
  # reFilc Plus
  refilc_plus:
    path: ../refilc_plus/

  flutter_feather_icons: ^2.0.0+1
  provider: ^6.1.1
  fl_chart: ^0.45.1
  url_launcher: ^6.2.5
  flutter_material_color_picker: ^1.1.0+2
  photo_view: ^0.14.0
  flutter_linkify: ^6.0.0
  flutter_custom_tabs: ^2.0.0+1
  flutter_markdown: ^0.6.20+1
  animations: ^2.0.11
  animated_list_plus: ^0.5.0
  confetti: ^0.7.0
  live_activities: ^1.9.1+1
  animated_flip_counter: ^0.2.5
  lottie: ^3.1.0
  rive: ^0.12.4
  animated_background: ^2.0.0
  home_widget: ^0.4.1
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.10+1
  background_fetch: ^1.2.2
  wtf_sliding_sheet: ^1.0.0
  package_info_plus: ^5.0.1
  dotted_border: ^2.0.0+3
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.2
  rounded_expansion_tile:
    git:
      url: https://github.com/kimaah/rounded_expansion_tile.git
  go_router: ^13.2.0
  flutter_expandable_fab: ^2.0.0
  intl: ^0.18.1
  i18n_extension: ^11.0.11
  auto_size_text: ^3.0.0
  connectivity_plus: ^5.0.2
  collection: ^1.18.0
  share_plus: ^7.2.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  image_crop:
    git:
      url: https://github.com/kimaah/image_crop.git
  uuid: ^4.3.3
  maps_launcher: ^2.2.0
  google_fonts: ^6.1.0
  flutter_any_logo: ^1.1.1
  custom_sliding_segmented_control: ^1.8.1
  get_it: ^7.6.7
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
