name: refilc
description: "Egy nem hivatalos e-KRÉTA kliens, diákoktól diákoknak."
homepage: https://refilc.hu
publish_to: "none"

version: 5.1.5+289

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # reFilc packages
  refilc_mobile_ui:
    path: "../refilc_mobile_ui/"
  # refilc_desktop_ui:
  #   path: "../refilc_desktop_ui/"
  refilc_kreta_api:
    path: "../refilc_kreta_api/"
  refilc_plus:
    path: "../refilc_plus"

  flutter_localizations:
    sdk: flutter
  i18n_extension: ^12.0.1
  sqflite: ^2.4.1
  intl: ^0.19.0
  provider: ^6.1.2
  http: ^1.3.0
  uuid: ^4.5.1
  html: ^0.15.5
  open_filex: ^4.6.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  share_plus: ^10.1.4
  connectivity_plus: ^6.1.3
  flutter_displaymode: ^0.6.0
  quick_actions: ^1.1.0
  animated_list_plus: ^0.5.2
  dynamic_color: ^1.7.0
  material_color_utilities: ^0.11.1
  crypto: ^3.0.6
  elegant_notification: ^2.4.1
  flutter_feather_icons: ^2.0.0+1
  animated_flip_counter: ^0.3.4
  animated_background: ^2.0.0
  dropdown_button2: ^2.3.9
  home_widget: ^0.7.0+1
  flutter_expandable_fab: ^2.3.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  animations: ^2.0.11
  background_fetch: ^1.3.7
  flutter_local_notifications: ^18.0.1
  package_info_plus: ^8.2.1
  screenshot: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  image_crop_plus: ^1.0.0
  maps_launcher: ^3.0.0+1
  google_fonts: ^6.2.1
  get_it: ^7.7.0
  xml: ^6.5.0
  carousel_slider: ^5.0.0
  flutter_portal: ^1.1.4
  shake_flutter: ^17.1.0

dependency_overrides:
  webview_flutter_wkwebview: 3.17.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  sqflite_common_ffi: ^2.3.4+4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/ic_splash.png
    - assets/icons/ic_rounded.png
    - assets/images/
    - assets/svg/menu_icons/
    - assets/other/dirtywords.xml
    - assets/svg/
    - assets/svg/cover_arts/

  fonts:
    - family: FilcIcons
      fonts:
        - asset: assets/fonts/FilcIcons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
    - family: FigTree
      fonts:
        - asset: assets/fonts/FigTree/Figtree-SemiBold.ttf
          weight: 500

flutter_launcher_icons:
  image_path: assets/icons/ic_android.png
  android: true
  adaptive_icon_background: "#7CA021"
  adaptive_icon_foreground: assets/icons/ic_launcher_foreground.png
  ios: false
  remove_alpha_ios: false
  web: false
  compress: true

flutter_native_splash:
  color: "#7CA021"
  image: assets/icons/ic_splash.png
  android_12:
    image: assets/icons/ic_splash.png
  android: true
  android_gravity: center
  ios: true
  ios_content_mode: center
  web: false
  compress: true