on:
  release:
    types: ["published"]

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Send message
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.NEW_RELEASE_WEBHOOK }}
        content: ${{ github.event.release.body }}
